FROM python:3.10-alpine

ENV CONTAINER_HOME=/shun

ADD . $CONTAINER_HOME
WORKDIR $CONTAINER_HOME

RUN apk add --no-cache build-base

RUN pip install --no-cache-dir --upgrade pip setuptools

RUN pip install -r $CONTAINER_HOME/requirements.txt

CMD ["python", "shun.py"]
